# Train configuration
trains:
  - id: cargo
    dcc-address: 0x007F # addr high | addr low
    dcc-speed-steps: 126
    calibration:
      - 5
      - 15
      - 30
      - 45
      - 60
      - 75
      - 90
      - 105
      - 120
    peripherals:
      - id: light
        bit: 4          # a value in range 0..31
        initial: 1
  - id: regional
    dcc-address: 0x0060
    dcc-speed-steps: 126
    calibration:
      - 5
      - 15
      - 30
      - 45
      - 60
      - 75
      - 90
      - 105
      - 120
    peripherals:
      - id: light
        bit: 4
        initial: 1
