# Track configuration
boards:
  - id: master
    segments:
      - id: seg1
        address: 0x01
        length: 0.0cm
      - id: seg2
        address: 0x02
        length: 0.0cm
      - id: seg3
        address: 0x03
        length: 0.0cm
      - id: seg4
        address: 0x04
        length: 0.0cm
      - id: seg5
        address: 0x05
        length: 0.0cm
      - id: seg6
        address: 0x06
        length: 0.0cm
      - id: seg7
        address: 0x07
        length: 0.0cm
      - id: seg8
        address: 0x08
        length: 0.0cm
      - id: seg9
        address: 0x09
        length: 0.0cm
      - id: seg10
        address: 0x0A
        length: 0.0cm
      - id: seg11
        address: 0x0B
        length: 0.0cm
      - id: seg12
        address: 0x0C
        length: 0.0cm
      - id: seg13
        address: 0x0D
        length: 0.0cm
      - id: seg14
        address: 0x0E
        length: 0.0cm
      - id: seg15
        address: 0x0F
        length: 0.0cm

  - id: lightcontrol
    signals-board:
      - id: signal1
        number: 0x06
        aspects:
          - id: red
            value: 0x01
          - id: green
            value: 0x00
        initial: red
      - id: signal2
        number: 0x05
        aspects:
          - id: red
            value: 0x01
          - id: green
            value: 0x00
        initial: red
      - id: signal3
        number: 0x04
        aspects:
          - id: red
            value: 0x01
          - id: green
            value: 0x00
        initial: red
      - id: signal4
        number: 0x03
        aspects:
          - id: red
            value: 0x01
          - id: green
            value: 0x00
        initial: red
      - id: signal5
        number: 0x02
        aspects:
          - id: red
            value: 0x01
          - id: green
            value: 0x00
        initial: red
      - id: signal6
        number: 0x01
        aspects:
          - id: red
            value: 0x01
          - id: green
            value: 0x00
        initial: red
      - id: signal7
        number: 0x00
        aspects:
          - id: red
            value: 0x01
          - id: green
            value: 0x00
        initial: red

  - id: onecontrol
    points-board:
      - id: point1
        number: 0x02
        aspects:
          - id: normal
            value: 0x01
          - id: reverse
            value: 0x00
        initial: normal
      - id: point2
        number: 0x00
        aspects:
          - id: normal
            value: 0x01
          - id: reverse
            value: 0x00
        initial: normal
      - id: point3
        number: 0x01
        aspects:
          - id: normal
            value: 0x01
          - id: reverse
            value: 0x00
        initial: normal
      - id: point4t
        number: 0x07
        aspects:
          - id: normal
            value: 0x01
          - id: reverse
            value: 0x00
        initial: normal
      - id: point5t
        number: 0x06
        aspects:
          - id: normal
            value: 0x01
          - id: reverse
            value: 0x00
        initial: normal
      - id: point6t
        number: 0x05
        aspects:
          - id: normal
            value: 0x01
          - id: reverse
            value: 0x00
        initial: normal
