# Block layout configuration: SWTbahnStandard
blocks:
  - id: block1
    length: 92.50cm
    main:
      - seg4
    overlaps:
      - seg3
      - seg5
    is_reversed: false
    direction: bidirectional
    trains:
      - cargo
      - passenger
    signals:
      - signal2
      - signal3
    limit: 300.0km/h
  - id: block2
    length: 105.50cm
    main:
      - seg8
    overlaps:
      - seg7
      - seg9
    is_reversed: false
    direction: bidirectional
    signals:
      - signal4
      - signal6
    limit: 350.0km/h
  - id: block3
    length: 142.10cm
    main:
      - seg12
    overlaps:
      - seg11
      - seg13
    is_reversed: false
    direction: bidirectional
    trains:
      - cargo
    signals:
      - signal7
      - signal8
  - id: block4
    length: 111.80cm
    main:
      - seg16
    overlaps:
      - seg15
      - seg17
    is_reversed: false
    direction: bidirectional
    signals:
      - signal10
      - signal12
  - id: block5
    length: 101.00cm
    main:
      - seg28
    overlaps:
      - seg27
      - seg29
    is_reversed: false
    direction: bidirectional
    signals:
      - signal9
      - signal11
  - id: block6
    length: 132.55cm
    main:
      - seg21
    overlaps:
      - seg20
      - seg22
    is_reversed: false
    direction: bidirectional
    signals:
      - signal13
      - signal5
  - id: block7
    length: 64.10cm
    main:
      - seg31
    overlaps:
      - seg30b
      - seg32b
    is_reversed: false
    direction: bidirectional
    signals:
      - signal14
      - signal15
  - id: buffer
    length: 20.00cm
    main:
      - seg1
    is_reversed: false
    direction: bidirectional
    signals:
      - signal1
platforms:
  - id: platform1
    length: 76.20cm
    main:
      - seg37
    overlaps:
      - seg36
      - seg38
    is_reversed: true
    direction: bidirectional
    signals:
      - signal16
      - signal17
  - id: platform2
    length: 83.80cm
    main:
      - seg40
    overlaps:
      - seg39
      - seg41
    is_reversed: true
    direction: bidirectional
    signals:
      - signal18
      - signal19
crossings:
  - id: crossing1
    segment: seg35
segments:
  - seg1
  - seg2
  - seg3
  - seg4
  - seg5
  - seg6
  - seg7
  - seg8
  - seg9
  - seg10
  - seg11
  - seg12
  - seg13
  - seg14
  - seg15
  - seg16
  - seg17
  - seg18
  - seg19
  - seg20
  - seg21
  - seg22
  - seg23
  - seg24
  - seg25
  - seg26
  - seg27
  - seg28
  - seg29
  - seg30a
  - seg30b
  - seg31
  - seg32a
  - seg32b
  - seg33
  - seg34
  - seg35
  - seg36
  - seg37
  - seg38
  - seg39
  - seg40
  - seg41
signals:
  - signal3
  - signal4
  - signal5
  - signal6
  - signal7
  - signal11
  - signal12
  - signal13
  - signal17
  - signal19
  - platformlights
  - signal1
  - signal2
  - signal8
  - signal9
  - signal10
  - signal14
  - signal15
  - signal16
  - signal18
signaltypes:
  - id: entry
    aspects:
      - aspect_caution
      - aspect_go
      - aspect_stop
  - id: exit
    aspects:
      - aspect_shunt
      - aspect_caution
      - aspect_go
      - aspect_stop
  - id: distant
    aspects:
      - aspect_caution
      - aspect_go
      - aspect_stop
  - id: block
    aspects:
      - aspect_go
      - aspect_stop
  - id: shunting
    aspects:
      - aspect_shunt
      - aspect_stop
  - id: halt
    aspects:
      - aspect_stop
  - id: platformlight
    aspects:
      - high
      - low
compositions:
peripheraltypes:
  - id: onebit
    aspects:
      - high
      - low