# Track configuration: SWTbahnUltraloop
boards:
  - id: master
    segments:
      - id: seg1
        address: 0x01
        length: 0.0cm
      - id: seg2
        address: 0x02
        length: 0.0cm
      - id: seg3
        address: 0x03
        length: 0.0cm
      - id: seg4
        address: 0x04
        length: 0.0cm
      - id: seg5
        address: 0x05
        length: 0.0cm
      - id: seg6
        address: 0x06
        length: 0.0cm
      - id: seg7
        address: 0x07
        length: 0.0cm
      - id: seg8
        address: 0x08
        length: 0.0cm
      - id: seg17
        address: 0x10
        length: 0.0cm
      - id: seg18
        address: 0x11
        length: 0.0cm
      - id: seg19
        address: 0x12
        length: 0.0cm
      - id: seg28
        address: 0x1B
        length: 0.0cm
      - id: seg29
        address: 0x1C
        length: 0.0cm
      - id: seg30
        address: 0x1D
        length: 0.0cm
      - id: seg31
        address: 0x1E
        length: 0.0cm
      - id: seg32
        address: 0x1F
        length: 0.0cm
  - id: onecontrol
    points-board:
      - id: point1
        number: 0x00
        aspects:
          - id: normal
            value: 0x01
          - id: reverse
            value: 0x00
        initial: normal
        segment: seg28
      - id: point2
        number: 0x01
        aspects:
          - id: normal
            value: 0x01
          - id: reverse
            value: 0x00
        initial: normal
        segment: seg31
      - id: decoupler
        number: 0x02
        aspects:
          - id: normal
            value: 0x01
          - id: reverse
            value: 0x00
        initial: reverse
        segment: seg1
      - id: point4
        number: 0x03
        aspects:
          - id: normal
            value: 0x01
          - id: reverse
            value: 0x00
        initial: normal
        segment: seg29
      - id: point5
        number: 0x04
        aspects:
          - id: normal
            value: 0x01
          - id: reverse
            value: 0x00
        initial: normal
        segment: seg2
      - id: servo_analog_linear
        number: 0x06
        aspects:
          - id: normal
            value: 0x01
          - id: reverse
            value: 0x00
        initial: normal
        segment: seg3
      - id: servo_analog_rotary
        number: 0x07
        aspects:
          - id: normal
            value: 0x01
          - id: reverse
            value: 0x00
        initial: normal
        segment: seg4
    signals-board:
      - id: signal1
        number: 0x08
        aspects:
          - id: aspect_go
            value: 0x01
          - id: aspect_stop
            value: 0x00
        initial: aspect_stop
        type: block
      - id: signal2
        number: 0x09
        aspects:
          - id: aspect_go
            value: 0x01
          - id: aspect_stop
            value: 0x00
        initial: aspect_stop
        type: block
      - id: signal3a
        number: 0x0A
        aspects:
          - id: aspect_go
            value: 0x01
          - id: aspect_stop
            value: 0x00
        initial: aspect_stop
        type: block
      - id: signal3b
        number: 0x0B
        aspects:
          - id: aspect_go
            value: 0x01
          - id: aspect_stop
            value: 0x00
        initial: aspect_stop
        type: block
      - id: signal4
        number: 0x0C
        aspects:
          - id: aspect_go
            value: 0x01
          - id: aspect_stop
            value: 0x00
        initial: aspect_stop
        type: block
      - id: signal5
        number: 0x0D
        aspects:
          - id: aspect_go
            value: 0x01
          - id: aspect_stop
            value: 0x00
        initial: aspect_stop
        type: block
      - id: signal6
        number: 0x0E
        aspects:
          - id: aspect_go
            value: 0x01
          - id: aspect_stop
            value: 0x00
        initial: aspect_stop
        type: block
      - id: signal7
        number: 0x0F
        aspects:
          - id: aspect_go
            value: 0x01
          - id: aspect_stop
            value: 0x00
        initial: aspect_stop
        type: block