# Track configuration
boards:
  - id: master
    segments:
      - id: seg1
        address: 0x00
      - id: seg2
        address: 0x01
      - id: seg3
        address: 0x02
      - id: seg4
        address: 0x03
      - id: seg5
        address: 0x04
      - id: seg6
        address: 0x05
      - id: seg7
        address: 0x06
      - id: seg8
        address: 0x07
      - id: seg9
        address: 0x08
      - id: seg10
        address: 0x09
      - id: seg11
        address: 0x0a
      - id: seg12
        address: 0x0b
      - id: seg13
        address: 0x0c
      - id: seg14
        address: 0x0d
      - id: seg15
        address: 0x0e
      - id: seg16
        address: 0x0f
        
      - id: seg17
        address: 0x10
      - id: seg18
        address: 0x11
      - id: seg19
        address: 0x12
      - id: seg20
        address: 0x13
      - id: seg21
        address: 0x14
      - id: seg22
        address: 0x15
      - id: seg23
        address: 0x16
      - id: seg24
        address: 0x17
      - id: seg25
        address: 0x18
      - id: seg26
        address: 0x19
      - id: seg27
        address: 0x1a
      - id: seg28
        address: 0x1b
      - id: seg29
        address: 0x1c
      - id: seg30
        address: 0x1d
      - id: seg31
        address: 0x1e
      - id: seg32
        address: 0x1f

  - id: onecontrol
    points-board:
      - id: point1
        number: 0x00
        aspects:
          - id: normal
            value: 0x01
          - id: reverse
            value: 0x00
        initial: normal
      - id: point2
        number: 0x01
        aspects:
          - id: normal
            value: 0x01
          - id: reverse
            value: 0x00
        initial: normal
      - id: decoupler
        number: 0x02
        aspects:
          - id: trigger
            value: 0x00
        initial: trigger
      - id: point4
        number: 0x03
        aspects:
          - id: normal
            value: 0x01
          - id: reverse
            value: 0x00
        initial: normal
      - id: point5
        number: 0x04
        aspects:
          - id: normal
            value: 0x01
          - id: reverse
            value: 0x00
        initial: normal
      - id: servo_analog_linear
        number: 0x06
        aspects:
          - id: normal
            value: 0x01
          - id: reverse
            value: 0x00
        initial: normal
      - id: servo_analog_rotary
        number: 0x07
        aspects:
          - id: normal
            value: 0x01
          - id: reverse
            value: 0x00
        initial: normal

    signals-board:
      - id: signal1
        number: 0x08
        aspects:
          - id: green
            value: 0x01
          - id: red
            value: 0x00
        initial: red
      - id: signal2
        number: 0x09
        aspects:
          - id: green
            value: 0x01
          - id: red
            value: 0x00
        initial: red
      - id: signal3a
        number: 0x0a
        aspects:
          - id: green
            value: 0x01
          - id: red
            value: 0x00
        initial: red
      - id: signal3b
        number: 0x0b
        aspects:
          - id: green
            value: 0x01
          - id: red
            value: 0x00
        initial: red
      - id: signal4
        number: 0x0c
        aspects:
          - id: green
            value: 0x01
          - id: red
            value: 0x00
        initial: red
      - id: signal5
        number: 0x0d
        aspects:
          - id: green
            value: 0x01
          - id: red
            value: 0x00
        initial: red
      - id: signal6
        number: 0x0e
        aspects:
          - id: green
            value: 0x01
          - id: red
            value: 0x00
        initial: red
      - id: signal7
        number: 0x0f
        aspects:
          - id: green
            value: 0x01
          - id: red
            value: 0x00
        initial: red
