# BiDiB board configuration: SWTbahnUltraloop
boards:
  - id: master
    unique-id: 0xDA000D6800D8EF
    features:
      - number: 0x03
        value: 0x14
      - number: 0x6E
        value: 0x00
  - id: onecontrol
    unique-id: 0x05000D7500EAED